
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Barlow_Semi_Condensed } from "next/font/google";
import "./theme-config.css";
import "./globals.css";

const barlow = Barlow_Semi_Condensed({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-barlow"
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Rock, Paper, Scissors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.variable}`}>
      <body>
        <Theme radius="large">
          {children}
        </Theme>
      </body>
    </html>
  );
}
